[root@che172rocky96 goflow2-deployment]# kubectl exec -it kafka-broker-0 -n default -- bash
Defaulted container "kafka" out of: kafka, prepare-config (init)
I have no name!@kafka-broker-0:/$ kafka-topics.sh --delete --bootstrap-server kafka:9092 --topic flows
I have no name!@kafka-broker-0:/$ kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic flows
Error while executing topic command : Topic 'flows' already exists.
[2025-07-24 06:58:18,254] ERROR org.apache.kafka.common.errors.TopicExistsException: Topic 'flows' already exists.
 (org.apache.kafka.tools.TopicCommand)
I have no name!@kafka-broker-0:/$ kafka-topics.sh --bootstrap-server localhost:9092 --describe --topic flows
Topic: flows    TopicId: JuIzU3PSQ66RMRazggQOjw PartitionCount: 1       ReplicationFactor: 1    Configs:
        Topic: flows    Partition: 0    Leader: 100     Replicas: 100   Isr: 100        Elr:    LastKnownElr:
I have no name!@kafka-broker-0:/$ kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic flows --from-beginning --group test-group-1
^CProcessed a total of 0 messages
I have no name!@kafka-broker-0:/$ kafka-console-producer.sh --bootstrap-server localhost:9092 --topic flows
>{"data":"test-123"}
>{"data":"test-1234"}
>^CI have no name!@kafka-broker-0:/$
I have no name!@kafka-broker-0:/$ kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic flows --from-beginning --group test-group-1
^CProcessed a total of 0 messages
I have no name!@kafka-broker-0:/$

I have no name!@kafka-broker-0:/$ kafka-run-class.sh kafka.tools.DumpLogSegments --files /bitnami/kafka/data/kafka-logs/flows-0/00000000000000000000.log --print-data-log
Dumping /bitnami/kafka/data/kafka-logs/flows-0/00000000000000000000.log
Log starting offset: 0
Exception in thread "main" java.nio.file.NoSuchFileException: /bitnami/kafka/data/kafka-logs/flows-0/00000000000000000000.log
        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source)
        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
        at java.base/java.nio.channels.FileChannel.open(Unknown Source)
        at org.apache.kafka.common.record.FileRecords.openChannel(FileRecords.java:474)
        at org.apache.kafka.common.record.FileRecords.open(FileRecords.java:429)
        at kafka.tools.DumpLogSegments$.dumpLog(DumpLogSegments.scala:280)
        at kafka.tools.DumpLogSegments$.$anonfun$main$1(DumpLogSegments.scala:80)
        at kafka.tools.DumpLogSegments$.$anonfun$main$1$adapted(DumpLogSegments.scala:71)
        at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
        at kafka.tools.DumpLogSegments$.main(DumpLogSegments.scala:71)
        at kafka.tools.DumpLogSegments.main(DumpLogSegments.scala)
